Repository kokonior/NodeJS-Projects, pull requests merged in 2021-10, with the labels that each got.

#1 Create ysl.js
  ysl.js
Labels: hacktoberfest-accepted, Create

#6 Update ysl.js
  ysl.js
Labels: enhancement, hacktoberfest-accepted

#5 Added Eilaluth.js [ covid 19 tracker with simple table in nodejs ]
  Eilaluth.js
Labels: enhancement, hacktoberfest-accepted

#4 Update ysl.js
  ysl.js
Labels: enhancement, hacktoberfest-accepted

#2 Create cnn.js
  cnn.js
Labels: hacktoberfest-accepted, Create

#7 Create asnjry.js
  asnjry.js
Labels: hacktoberfest-accepted, Create

#8 Update asnjry.js
  asnjry.js
Labels: hacktoberfest-accepted

#9 Update asnjry.js
  asnjry.js
Labels: hacktoberfest-accepted

#10 Update asnjry.js
  asnjry.js
Labels: hacktoberfest-accepted

#11 [hasbi] add array to object file
  hasbi-array-to-object.js
Labels: hacktoberfest-accepted

#12 Create bissmillah.js
  bissmillah.js
Labels: hacktoberfest-accepted, Create

#13 Create Hello_world_example.js
  Hello_world_example.js
Labels: hacktoberfest-accepted, Create

#15 fix readme.md and upload my project
  README.md
  absensi_isal.js
Labels: enhancement, good first issue, hacktoberfest-accepted

#14 tambah game js batu gunting kertas
  scisorsgame.js
Labels: enhancement, hacktoberfest-accepted

#18 Update README.md
  README.md
Labels: hacktoberfest-accepted

#17 Create chossopian.js
  chossopian.js
Labels: hacktoberfest-accepted, Create

#16 Simple x digit number generator
  rand_x_number.js
Labels: enhancement, hacktoberfest-accepted

#20 Create connectwallet.js
  connectwallet.js
Labels: hacktoberfest-accepted, Create

#21 TechifyAu
  .idea/.gitignore
  .idea/NodeJS-Projects.iml
  .idea/discord.xml
  .idea/modules.xml
  .idea/vcs.xml
  TechifyAU.js
Labels: hacktoberfest-accepted

#22 Create autoCreateMSEdu.js
  autoCreateMSEdu.js
Labels: hacktoberfest-accepted, Create

#23 alakaadutz
  genre.js
Labels: hacktoberfest-accepted

#24 Create twitter
  twitter
Labels: hacktoberfest-accepted, Create

#25 Create serverHTTP
  serverHTTP
Labels: hacktoberfest-accepted

#27 add firebase storage function
  firebaseStorage.js
Labels: hacktoberfest-accepted

#30 Create Tes
  Rashid/Tes
Labels: hacktoberfest-accepted, Create

#31 added License
  LICENSE.md
Labels: hacktoberfest-accepted

#68 add my small node program
  my_small_node.js
Labels: hacktoberfest-accepted
